version: "2"
services:
   db:
     image: mysql:5.7
     volumes:
       - ./db-data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     container_name: wp_test_db

   wordpress:
     depends_on:
       - db
     image: jburger/wordpress-xdebug
     ports:
       - "${WORDPRESS_PORT}:80"
     restart: always
     volumes:
       - ./wordpress:/var/www/html
     environment:
       VIRTUAL_HOST: wpress.dev
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
       PHP_IDE_CONFIG: "serverName=docker"
     container_name: wp_test

   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "${PHPMYADMIN_PORT}:80"  
    restart: always
    container_name: wp_phpmyadmin
    environment:
       VIRTUAL_HOST: phpma.dev

#networks:
 # default:
  #  external:
   #   name: nginx-proxy