version: "2"
services:
   db-wpress:
     image: mysql:5.7
     volumes:
       - ./db-data:/var/lib/mysql
     expose:
       - 3306
     restart: always
     environment:
       VIRTUAL_HOST: wpress-db.dev
       MYSQL_ROOT_PASSWORD: haslo
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     container_name: "${INSTANCE_PREFIX}_test_db"

   wordpress:
     depends_on:
       - db-wpress
     image: jburger/wordpress-xdebug
     expose:
       - 80
     restart: always
     volumes:
       - ./wordpress:/var/www/html
     environment:
       VIRTUAL_HOST: wpress.dev
       WORDPRESS_DB_HOST: db-wpress
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
       PHP_IDE_CONFIG: "serverName=docker"
     container_name: "${INSTANCE_PREFIX}_worpress"

   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db-wpress
    expose:
      - 80
    restart: always
    container_name: "${INSTANCE_PREFIX}_phmyadmin"
    environment:
       VIRTUAL_HOST: wpress-phpmy.dev

networks:
  default:
    external:
      name: nginx-proxy