version: "2"
services:
   db:
     image: mysql:5.7
     volumes:
       - ./db-data:/var/lib/mysql
     expose:
       - 3306
     ports:
       - "3306:3306"  
     restart: always
     environment:
       VIRTUAL_HOST: wpress-db.dev
       MYSQL_ROOT_PASSWORD: haslo
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     container_name: "${INSTANCE_PREFIX}_test_db"

   wordpress:
     image: jburger/wordpress-xdebug
     depends_on:
       - db
     expose:
       - 80
     restart: always
     volumes:
       - ./wordpress:/var/www/html
       - ./myphp.ini:/usr/local/etc/php/conf.d/myphp.ini
     environment:
       VIRTUAL_HOST: wpress.dev
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       XDEBUG_CONFIG: "remote_host=${DOCKER_LOCAL_IP} idekey=xdebug"
       PHP_IDE_CONFIG: "serverName=docker"
     container_name: "${INSTANCE_PREFIX}_worpress"

   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
       - db
    depends_on:
       - db
    expose:
      - 80
    restart: always
    container_name: "${INSTANCE_PREFIX}_phmyadmin"
    environment:
       VIRTUAL_HOST: wpress-phpmy.dev

networks:
  default:
    external:
      name: nginx-proxy